INDOOR_SCENES = {
    # Explicit indoor from Places365
    'basketball_court/indoor', 'bazaar/indoor', 'booth/indoor', 'bow_window/indoor',
    'bus_station/indoor', 'church/indoor', 'escalator/indoor', 'flea_market/indoor',
    'florist_shop/indoor', 'garage/indoor', 'general_store/indoor', 'greenhouse/indoor',
    'gymnasium/indoor', 'hangar/indoor', 'ice_skating_rink/indoor', 'jacuzzi/indoor',
    'library/indoor', 'market/indoor', 'movie_theater/indoor', 'museum/indoor',
    'parking_garage/indoor', 'pub/indoor', 'shopping_mall/indoor', 'stage/indoor',
    'swimming_pool/indoor',
    
    # Inherently indoor scenes
    'airplane_cabin', 'alcove', 'amusement_arcade', 'aquarium', 'arcade', 'archive',
    'arena/hockey', 'arena/performance', 'arena/rodeo', 'art_gallery', 'art_school',
    'art_studio', 'artists_loft', 'assembly_line', 'atrium/public', 'attic', 'auditorium',
    'auto_factory', 'auto_showroom', 'bakery/shop', 'balcony/interior', 'ball_pit',
    'ballroom', 'bank_vault', 'banquet_hall', 'bar', 'barn', 'basement', 'bathroom',
    'beauty_salon', 'bedchamber', 'bedroom', 'beer_hall', 'berth', 'biology_laboratory',
    'boathouse', 'bookstore', 'bowling_alley', 'boxing_ring', 'burial_chamber',
    'bus_interior', 'butchers_shop', 'cafeteria', 'candy_store', 'car_interior',
    'carrousel', 'catacomb', 'chalet', 'chemistry_lab', 'childs_room', 'classroom',
    'clean_room', 'closet', 'clothing_store', 'cockpit', 'coffee_shop', 'computer_room',
    'conference_center', 'conference_room', 'corridor', 'courthouse', 'delicatessen',
    'department_store', 'dining_hall', 'dining_room', 'discotheque', 'dorm_room',
    'dressing_room', 'drugstore', 'elevator/door', 'elevator_lobby', 'elevator_shaft',
    'embassy', 'engine_room', 'entrance_hall', 'fabric_store', 'fastfood_restaurant',
    'fire_escape', 'fire_station', 'food_court', 'galley', 'gift_shop', 'hardware_store',
    'home_office', 'home_theater', 'hospital', 'hospital_room', 'hotel_room', 'house',
    'ice_cream_parlor', 'jail_cell', 'jewelry_shop', 'kasbah', 'kindergarden_classroom',
    'kitchen', 'laundromat', 'lecture_room', 'legislative_chamber', 'lighthouse',
    'living_room', 'loading_dock', 'lobby', 'lock_chamber', 'locker_room', 'mansion',
    'manufactured_home', 'martial_arts_gym', 'mausoleum', 'medina', 'mezzanine',
    'motel', 'music_studio', 'natural_history_museum', 'nursery', 'nursing_home',
    'oast_house', 'office', 'office_building', 'office_cubicles', 'operating_room',
    'orchestra_pit', 'pagoda', 'palace', 'pantry', 'pet_shop', 'pharmacy', 'phone_booth',
    'physics_laboratory', 'pizzeria', 'playroom', 'porch', 'reception', 'recreation_room',
    'repair_shop', 'restaurant', 'restaurant_kitchen', 'sauna', 'schoolhouse',
    'science_museum', 'server_room', 'shed', 'shoe_shop', 'shopfront', 'shower',
    'stable', 'staircase', 'storage_room', 'subway_station/platform', 'supermarket',
    'sushi_bar', 'television_room', 'television_studio', 'temple/asia', 'throne_room',
    'ticket_booth', 'toyshop', 'train_interior', 'train_station/platform', 'tree_house',
    'utility_room', 'veterinarians_office', 'waiting_room', 'wet_bar', 'youth_hostel'
}